name: todobus
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.2+12

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  http: ^1.4.0
  logger: ^2.5.0
  provider: ^6.1.5
  package_info_plus: ^8.3.0
  device_info_plus: ^11.4.0
  flutter_platform_widgets: ^8.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  table_calendar: ^3.1.3
  flutter_launcher_icons: ^0.14.3
  share_plus: ^11.0.0
  url_launcher: ^6.3.1
  firebase_core: ^2.27.1
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.1.0
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  add_2_calendar: ^3.0.1
  device_calendar: ^4.3.3
  timezone: ^0.9.4
  dio: ^5.1.1
  fluttertoast: ^8.2.1
  flutter_svg: ^2.0.5
  flutter_native_splash: ^2.2.19
  firebase_analytics: ^10.2.1
  flutter_secure_storage: ^8.0.0
  json_annotation: ^4.8.0
  percent_indicator: ^4.2.3
  cached_network_image: ^3.2.3
  infinite_scroll_pagination: ^3.2.0
  flutter_markdown: ^0.6.14
  photo_view: ^0.14.0
  file_picker: ^5.3.0
  flutter_app_badger: ^1.5.0
  uuid: ^3.0.7
  platform: ^3.1.0
  flutter_linkify: ^6.0.0
  photo_manager: ^2.6.0
  flutter_spinkit: ^5.2.0
  connectivity_plus: ^4.0.0
  animated_text_kit: ^4.2.2
  flutter_staggered_animations: ^1.1.1
  flutter_cached_pdfview: ^0.4.1
  disable_battery_optimization: ^1.1.1
  video_player: ^2.9.5
  google_generative_ai: ^0.4.6
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/onboarding/
    - assets/onboarding/1.mp4
    - assets/onboarding/2.mp4
    - assets/onboarding/3.mp4
    - .env
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# Flutter Launcher Icons yapılandırması
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon.png"

# Flutter Native Splash yapılandırması
flutter_native_splash:
  # Native splash'i splash_screen.dart ile aynı yapmak için
  color: "#FFFFFF"  # Beyaz arka plan
  image: "assets/splash.png" # Splash görüntüsünü geri ekliyoruz
  color_dark: "#FFFFFF"  # Koyu tema için de beyaz
  image_dark: "assets/splash.png" # Koyu tema için de aynı görüntü
  
  android_12:
    image: "assets/splash.png" # Android 12 için de aynı görüntü
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#FFFFFF"
    
  fullscreen: true  # Fullscreen'i açıyoruz splash_screen.dart gibi
  android: true
  ios: true
  web: false
  
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  
  # Animasyon ve branding kaldırılmış durumda
  
  # Durumlar
  android_screen_orientation: portrait
